------------------------------------------------------------
-- 1. TABLAS
------------------------------------------------------------

-- TABLA USUARIO
CREATE TABLE Usuario (
    cedula            INT PRIMARY KEY,
    nombre            VARCHAR2(40) NOT NULL,
    email             VARCHAR2(60) NOT NULL,
    nombre_usuario    VARCHAR2(20) NOT NULL,
    contrasena        VARCHAR2(20) NOT NULL,
    rol               VARCHAR2(20) NOT NULL,
    ruta_imagen       VARCHAR2(70),
    accedio           NUMBER(38,0),
    CONSTRAINT chk_email CHECK (email LIKE '%@%.%')
);

-- TABLA CULTIVO (Con ID_USUARIO integrado)
CREATE TABLE Cultivo (
    id_planta                INT PRIMARY KEY,
    nombre_planta            VARCHAR2(20) NOT NULL,
    descripcion              VARCHAR2(50),
    ruta_imagen              VARCHAR2(50),
    nivel_optimo_humedad     FLOAT CHECK (nivel_optimo_humedad BETWEEN 0 AND 100),
    nivel_optimo_temperatura FLOAT CHECK (nivel_optimo_temperatura BETWEEN -10 AND 60),
    nivel_optimo_luz         FLOAT,
    id_usuario               NUMBER -- Columna agregada directamente
);

-- TABLA HISTORIAL RIEGO (Con ID_PLANTA integrado)
CREATE TABLE Historial_Riego (
    id_historial_riego INT PRIMARY KEY,
    fecha_hora         DATE NOT NULL,
    humedad            FLOAT,
    temperatura        FLOAT,
    id_planta          NUMBER -- Columna agregada por modificación
);

-- TABLA HISTORIAL ALERTAS
CREATE TABLE Historial_Alertas (
    id_alerta     NUMBER(38) PRIMARY KEY,
    fecha_hora    DATE NOT NULL,
    tipo_alerta   VARCHAR2(50) NOT NULL,
    descripcion   VARCHAR2(50),
    nivel_critico VARCHAR2(20),
    estado        NUMBER(1)
);

-- TABLA REGISTRO CLIMATICO (Con ID_PLANTA integrado)
CREATE TABLE REGISTRO_CLIMATICO (
    ID_REGISTRO      NUMBER PRIMARY KEY,
    FECHA_HORA       DATE DEFAULT SYSDATE NOT NULL,
    HUMEDAD_SUELO    FLOAT,
    HUMEDAD_AMBIENTE FLOAT,
    TEMPERATURA_AMB  FLOAT,
    VIENTO           FLOAT,
    ID_PLANTA        NUMBER -- Columna agregada por modificación
);

-- TABLA HUMEDAD PORCENTAJE
CREATE TABLE humedad_porcentaje (
  id_humedad NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  porcentaje NUMBER(3) NOT NULL,
  fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- TABLA TEMPERATURA (Con ID_PLANTA integrado)
CREATE TABLE TEMPERATURA (
    ID_TEMPERATURA  NUMBER PRIMARY KEY,
    FECHA_HORA      DATE DEFAULT SYSDATE NOT NULL,
    TEMP_AMBIENTE   FLOAT NOT NULL,
    TEMP_SUELO      FLOAT,
    OBSERVACION     VARCHAR2(100),
    ID_PLANTA       NUMBER -- Columna agregada por modificación
);

------------------------------------------------------------
-- 2. SECUENCIAS
------------------------------------------------------------
CREATE SEQUENCE seq_temperatura START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_cultivo START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_historial_riego START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_alertas START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_registro_climatico START WITH 1 INCREMENT BY 1 NOCACHE;

------------------------------------------------------------
-- 3. TRIGGERS
------------------------------------------------------------

-- Trigger ID Temperatura
CREATE OR REPLACE TRIGGER trg_temperatura_id
BEFORE INSERT ON TEMPERATURA
FOR EACH ROW
WHEN (NEW.ID_TEMPERATURA IS NULL)
BEGIN
  SELECT seq_temperatura.NEXTVAL INTO :NEW.ID_TEMPERATURA FROM DUAL;
END;
/

-- Trigger ID Cultivo
CREATE OR REPLACE TRIGGER trg_cultivo_id
BEFORE INSERT ON Cultivo
FOR EACH ROW
WHEN (NEW.id_planta IS NULL)
BEGIN
  SELECT seq_cultivo.NEXTVAL INTO :NEW.id_planta FROM DUAL;
END;
/

-- Trigger ID Historial Riego
CREATE OR REPLACE TRIGGER trg_historial_id
BEFORE INSERT ON Historial_Riego
FOR EACH ROW
WHEN (NEW.id_historial_riego IS NULL)
BEGIN
  SELECT seq_historial_riego.NEXTVAL INTO :NEW.id_historial_riego FROM DUAL;
END;
/

-- Trigger ID Alertas
CREATE OR REPLACE TRIGGER trg_alertas_id
BEFORE INSERT ON Historial_Alertas
FOR EACH ROW
WHEN (NEW.id_alerta IS NULL)
BEGIN
  SELECT seq_alertas.NEXTVAL INTO :NEW.id_alerta FROM DUAL;
END;
/

-- Trigger ID Registro Climatico
CREATE OR REPLACE TRIGGER trg_registro_climatico_id
BEFORE INSERT ON REGISTRO_CLIMATICO
FOR EACH ROW
WHEN (NEW.ID_REGISTRO IS NULL)
BEGIN
  SELECT seq_registro_climatico.NEXTVAL INTO :NEW.ID_REGISTRO FROM DUAL;
END;
/

-- Trigger Defaults Usuario
CREATE OR REPLACE TRIGGER trg_usuario_defaults
BEFORE INSERT OR UPDATE ON Usuario
FOR EACH ROW
BEGIN
  IF :NEW.email IS NOT NULL THEN
    :NEW.email := LOWER(TRIM(:NEW.email));
  END IF;
  IF :NEW.accedio IS NULL THEN
    :NEW.accedio := 0;
  END IF;
END;
/

-- Trigger Limpieza Humedad Porcentaje
CREATE OR REPLACE TRIGGER trg_limpiar_humedad
AFTER INSERT ON humedad_porcentaje
DECLARE
  total NUMBER;
BEGIN
  SELECT COUNT(*) INTO total FROM humedad_porcentaje;
  IF total >= 1000 THEN
    EXECUTE IMMEDIATE 'TRUNCATE TABLE humedad_porcentaje';
  END IF;
END;
/

-- Validación Usuario (Longitud Password)
CREATE OR REPLACE TRIGGER trg_usuario_pass_len
BEFORE INSERT OR UPDATE ON Usuario
FOR EACH ROW
BEGIN
    IF LENGTH(:NEW.contrasena) < 6 THEN
        RAISE_APPLICATION_ERROR(-20002, 'La contraseña debe tener mínimo 6 caracteres.');
    END IF;
END;
/

-- Validación Usuario (Nombre sin números)
CREATE OR REPLACE TRIGGER trg_usuario_nombre_val
BEFORE INSERT OR UPDATE ON Usuario
FOR EACH ROW
BEGIN
    IF REGEXP_LIKE(:NEW.nombre, '[0-9]') THEN
        RAISE_APPLICATION_ERROR(-20004, 'El nombre no puede contener números.');
    END IF;
END;
/

------------------------------------------------------------
-- 4. PAQUETES (PACKAGES) - VERSIONES ACTUALIZADAS
------------------------------------------------------------

-- =========================================================
-- PKG_USUARIO (Sin cambios solicitados)
-- =========================================================
CREATE OR REPLACE PACKAGE pkg_usuario AS
  PROCEDURE insertar_usuario(
      p_cedula        IN NUMBER,
      p_nombre        IN VARCHAR2,
      p_email         IN VARCHAR2,
      p_nombre_usuario IN VARCHAR2,
      p_contrasena    IN VARCHAR2,
      p_rol           IN VARCHAR2,
      p_ruta_imagen   IN VARCHAR2,
      p_estado        OUT NUMBER,
      p_mensaje       OUT VARCHAR2
  );
  PROCEDURE actualizar_usuario(
      p_cedula        IN NUMBER,
      p_nombre        IN VARCHAR2,
      p_email         IN VARCHAR2,
      p_nombre_usuario IN VARCHAR2,
      p_contrasena    IN VARCHAR2,
      p_rol           IN VARCHAR2,
      p_ruta_imagen   IN VARCHAR2,
      p_estado        OUT NUMBER,
      p_mensaje       OUT VARCHAR2
  );
  PROCEDURE eliminar_usuario(
      p_cedula IN NUMBER,
      p_estado OUT NUMBER,
      p_mensaje OUT VARCHAR2
  );
  PROCEDURE buscar_por_id(
      p_cedula IN NUMBER,
      p_cursor OUT SYS_REFCURSOR
  );
  PROCEDURE listar_usuarios(
      p_cursor OUT SYS_REFCURSOR
  );
  PROCEDURE buscar_por_credenciales(
      p_usuario IN VARCHAR2,
      p_contrasena IN VARCHAR2,
      p_cursor OUT SYS_REFCURSOR
  );
END pkg_usuario;
/

CREATE OR REPLACE PACKAGE BODY pkg_usuario AS

  PROCEDURE insertar_usuario(
      p_cedula IN NUMBER,
      p_nombre IN VARCHAR2,
      p_email IN VARCHAR2,
      p_nombre_usuario IN VARCHAR2,
      p_contrasena IN VARCHAR2,
      p_rol IN VARCHAR2,
      p_ruta_imagen IN VARCHAR2,
      p_estado OUT NUMBER,
      p_mensaje OUT VARCHAR2
  ) AS
  BEGIN
      INSERT INTO Usuario(cedula, nombre, email, nombre_usuario, contrasena, rol, ruta_imagen)
      VALUES(p_cedula, p_nombre, p_email, p_nombre_usuario, p_contrasena, p_rol, p_ruta_imagen);
      p_estado := 1;
      p_mensaje := 'Usuario insertado correctamente';
  EXCEPTION
      WHEN OTHERS THEN
          p_estado := 0;
          p_mensaje := SQLERRM;
  END insertar_usuario;

  PROCEDURE actualizar_usuario(
      p_cedula IN NUMBER,
      p_nombre IN VARCHAR2,
      p_email IN VARCHAR2,
      p_nombre_usuario IN VARCHAR2,
      p_contrasena IN VARCHAR2,
      p_rol IN VARCHAR2,
      p_ruta_imagen IN VARCHAR2,
      p_estado OUT NUMBER,
      p_mensaje OUT VARCHAR2
  ) AS
  BEGIN
      UPDATE Usuario
      SET nombre = p_nombre,
          email = p_email,
          nombre_usuario = p_nombre_usuario,
          contrasena = p_contrasena,
          rol = p_rol,
          ruta_imagen = p_ruta_imagen
      WHERE cedula = p_cedula;

      IF SQL%ROWCOUNT = 0 THEN
        p_estado := 0;
        p_mensaje := 'No se encontró el usuario para actualizar';
      ELSE
        p_estado := 1;
        p_mensaje := 'Usuario actualizado correctamente';
      END IF;
  EXCEPTION
      WHEN OTHERS THEN
          p_estado := 0;
          p_mensaje := SQLERRM;
  END actualizar_usuario;

  PROCEDURE eliminar_usuario(
      p_cedula IN NUMBER,
      p_estado OUT NUMBER,
      p_mensaje OUT VARCHAR2
  ) AS
  BEGIN
      DELETE FROM Usuario WHERE cedula = p_cedula;

      IF SQL%ROWCOUNT = 0 THEN
        p_estado := 0;
        p_mensaje := 'No se encontró el usuario para eliminar';
      ELSE
        p_estado := 1;
        p_mensaje := 'Usuario eliminado correctamente';
      END IF;
  EXCEPTION
      WHEN OTHERS THEN
          p_estado := 0;
          p_mensaje := SQLERRM;
  END eliminar_usuario;

  PROCEDURE buscar_por_id(
      p_cedula IN NUMBER,
      p_cursor OUT SYS_REFCURSOR
  ) AS
  BEGIN
      OPEN p_cursor FOR SELECT * FROM Usuario WHERE cedula = p_cedula;
  END buscar_por_id;

  PROCEDURE listar_usuarios(
      p_cursor OUT SYS_REFCURSOR
  ) AS
  BEGIN
      OPEN p_cursor FOR SELECT * FROM Usuario ORDER BY cedula;
  END listar_usuarios;

  PROCEDURE buscar_por_credenciales(
      p_usuario IN VARCHAR2,
      p_contrasena IN VARCHAR2,
      p_cursor OUT SYS_REFCURSOR
  ) AS
  BEGIN
      OPEN p_cursor FOR
          SELECT *
          FROM Usuario
          WHERE nombre_usuario = p_usuario
            AND contrasena = p_contrasena;
  END buscar_por_credenciales;
END pkg_usuario;
/

-- =========================================================
-- PKG_CULTIVO (Sin cambios solicitados)
-- =========================================================
CREATE OR REPLACE PACKAGE pkg_cultivo AS
    PROCEDURE insertar_cultivo(
        p_nombre_planta IN cultivo.nombre_planta%TYPE,
        p_descripcion   IN cultivo.descripcion%TYPE,
        p_ruta_imagen   IN cultivo.ruta_imagen%TYPE,
        p_humedad       IN cultivo.nivel_optimo_humedad%TYPE,
        p_temperatura   IN cultivo.nivel_optimo_temperatura%TYPE,
        p_luz           IN cultivo.nivel_optimo_luz%TYPE,
        p_id OUT cultivo.id_planta%TYPE
    );
    PROCEDURE actualizar_cultivo(
        p_id            IN cultivo.id_planta%TYPE,
        p_nombre_planta IN cultivo.nombre_planta%TYPE,
        p_descripcion   IN cultivo.descripcion%TYPE,
        p_ruta_imagen   IN cultivo.ruta_imagen%TYPE,
        p_humedad       IN cultivo.nivel_optimo_humedad%TYPE,
        p_temperatura   IN cultivo.nivel_optimo_temperatura%TYPE,
        p_luz           IN cultivo.nivel_optimo_luz%TYPE
    );
    PROCEDURE eliminar_cultivo(p_id IN cultivo.id_planta%TYPE);
    PROCEDURE obtener_por_id(
        p_id IN cultivo.id_planta%TYPE,
        p_cursor OUT SYS_REFCURSOR
    );
    PROCEDURE obtener_todos(p_cursor OUT SYS_REFCURSOR);
END pkg_cultivo;
/

CREATE OR REPLACE PACKAGE BODY pkg_cultivo AS
    PROCEDURE insertar_cultivo(
        p_nombre_planta IN cultivo.nombre_planta%TYPE,
        p_descripcion   IN cultivo.descripcion%TYPE,
        p_ruta_imagen   IN cultivo.ruta_imagen%TYPE,
        p_humedad       IN cultivo.nivel_optimo_humedad%TYPE,
        p_temperatura   IN cultivo.nivel_optimo_temperatura%TYPE,
        p_luz           IN cultivo.nivel_optimo_luz%TYPE,
        p_id OUT cultivo.id_planta%TYPE
    ) IS
    BEGIN
        INSERT INTO cultivo(nombre_planta, descripcion, ruta_imagen,
                            nivel_optimo_humedad, nivel_optimo_temperatura,
                            nivel_optimo_luz)
        VALUES (p_nombre_planta, p_descripcion, p_ruta_imagen,
                p_humedad, p_temperatura, p_luz)
        RETURNING id_planta INTO p_id;
    END insertar_cultivo;

    PROCEDURE actualizar_cultivo(
        p_id            IN cultivo.id_planta%TYPE,
        p_nombre_planta IN cultivo.nombre_planta%TYPE,
        p_descripcion   IN cultivo.descripcion%TYPE,
        p_ruta_imagen   IN cultivo.ruta_imagen%TYPE,
        p_humedad       IN cultivo.nivel_optimo_humedad%TYPE,
        p_temperatura   IN cultivo.nivel_optimo_temperatura%TYPE,
        p_luz           IN cultivo.nivel_optimo_luz%TYPE
    ) IS
    BEGIN
        UPDATE cultivo
        SET nombre_planta = p_nombre_planta,
            descripcion   = p_descripcion,
            ruta_imagen   = p_ruta_imagen,
            nivel_optimo_humedad = p_humedad,
            nivel_optimo_temperatura = p_temperatura,
            nivel_optimo_luz = p_luz
        WHERE id_planta = p_id;
    END actualizar_cultivo;

    PROCEDURE eliminar_cultivo(p_id IN cultivo.id_planta%TYPE) IS
    BEGIN
        DELETE FROM cultivo WHERE id_planta = p_id;
    END eliminar_cultivo;

    PROCEDURE obtener_por_id(
        p_id IN cultivo.id_planta%TYPE,
        p_cursor OUT SYS_REFCURSOR
    ) IS
    BEGIN
        OPEN p_cursor FOR SELECT * FROM cultivo WHERE id_planta = p_id;
    END obtener_por_id;

    PROCEDURE obtener_todos(p_cursor OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN p_cursor FOR SELECT * FROM cultivo;
    END obtener_todos;
END pkg_cultivo;
/

-- =========================================================
-- PKG_HUMEDAD_PORCENTAJE (Sin cambios solicitados)
-- =========================================================
CREATE OR REPLACE PACKAGE PKG_HUMEDAD_PORCENTAJE AS
    PROCEDURE SP_INSERTAR_HUMEDAD(
        p_porcentaje     IN  humedad_porcentaje.porcentaje%TYPE,
        p_resultado      OUT NUMBER,
        p_mensaje        OUT VARCHAR2,
        p_id_generado    OUT NUMBER
    );
    PROCEDURE SP_OBTENER_TODOS(
        p_cursor OUT SYS_REFCURSOR
    );
END PKG_HUMEDAD_PORCENTAJE;
/

CREATE OR REPLACE PACKAGE BODY PKG_HUMEDAD_PORCENTAJE AS
    PROCEDURE SP_INSERTAR_HUMEDAD(
        p_porcentaje     IN  humedad_porcentaje.porcentaje%TYPE,
        p_resultado      OUT NUMBER,
        p_mensaje        OUT VARCHAR2,
        p_id_generado    OUT NUMBER
    ) IS
    BEGIN
        INSERT INTO humedad_porcentaje(porcentaje)
        VALUES (p_porcentaje)
        RETURNING id_humedad INTO p_id_generado;

        p_resultado := 1;
        p_mensaje := 'Registro insertado correctamente';
    EXCEPTION
        WHEN OTHERS THEN
            p_resultado := 0;
            p_mensaje := 'Error: ' || SQLERRM;
            p_id_generado := NULL;
    END SP_INSERTAR_HUMEDAD;

    PROCEDURE SP_OBTENER_TODOS(
        p_cursor OUT SYS_REFCURSOR
    ) IS
    BEGIN
        OPEN p_cursor FOR
            SELECT id_humedad, porcentaje, fecha_registro
            FROM humedad_porcentaje
            ORDER BY fecha_registro DESC;
    END SP_OBTENER_TODOS;
END PKG_HUMEDAD_PORCENTAJE;
/

-- =========================================================
-- PKG_TEMPERATURA (ACTUALIZADO: Soporte ID_PLANTA)
-- =========================================================
CREATE OR REPLACE PACKAGE PKG_TEMPERATURA AS
    PROCEDURE SP_INSERTAR_TEMPERATURA(
        p_temp_ambiente   IN TEMPERATURA.TEMP_AMBIENTE%TYPE,
        p_temp_suelo      IN TEMPERATURA.TEMP_SUELO%TYPE,
        p_observacion     IN TEMPERATURA.OBSERVACION%TYPE,
        p_id_planta       IN NUMBER,  -- Nuevo parámetro
        p_id_generado     OUT NUMBER,
        p_estado          OUT NUMBER,
        p_mensaje         OUT VARCHAR2
    );
    PROCEDURE SP_ACTUALIZAR_TEMPERATURA(
        p_id_temperatura  IN TEMPERATURA.ID_TEMPERATURA%TYPE,
        p_temp_ambiente   IN TEMPERATURA.TEMP_AMBIENTE%TYPE,
        p_temp_suelo      IN TEMPERATURA.TEMP_SUELO%TYPE,
        p_observacion     IN TEMPERATURA.OBSERVACION%TYPE,
        p_estado          OUT NUMBER,
        p_mensaje         OUT VARCHAR2
    );
    PROCEDURE SP_ELIMINAR_TEMPERATURA(
        p_id_temperatura  IN TEMPERATURA.ID_TEMPERATURA%TYPE,
        p_estado          OUT NUMBER,
        p_mensaje         OUT VARCHAR2
    );
    PROCEDURE SP_OBTENER_POR_ID(
        p_id_temperatura  IN TEMPERATURA.ID_TEMPERATURA%TYPE,
        p_cursor          OUT SYS_REFCURSOR,
        p_estado          OUT NUMBER,
        p_mensaje         OUT VARCHAR2
    );
    PROCEDURE SP_MOSTRAR_TODOS(
        p_cursor          OUT SYS_REFCURSOR,
        p_estado          OUT NUMBER,
        p_mensaje         OUT VARCHAR2
    );
END PKG_TEMPERATURA;
/

CREATE OR REPLACE PACKAGE BODY PKG_TEMPERATURA AS

    PROCEDURE SP_INSERTAR_TEMPERATURA(
        p_temp_ambiente   IN TEMPERATURA.TEMP_AMBIENTE%TYPE,
        p_temp_suelo      IN TEMPERATURA.TEMP_SUELO%TYPE,
        p_observacion     IN TEMPERATURA.OBSERVACION%TYPE,
        p_id_planta       IN NUMBER,
        p_id_generado     OUT NUMBER,
        p_estado          OUT NUMBER,
        p_mensaje         OUT VARCHAR2
    ) AS
    BEGIN
        SELECT seq_temperatura.NEXTVAL INTO p_id_generado FROM DUAL;

        INSERT INTO TEMPERATURA (
            ID_TEMPERATURA, TEMP_AMBIENTE, TEMP_SUELO, OBSERVACION, ID_PLANTA
        ) VALUES (
            p_id_generado, p_temp_ambiente, p_temp_suelo, p_observacion, p_id_planta
        );

        p_estado := 1;
        p_mensaje := 'Registro de temperatura con planta insertado correctamente';
    EXCEPTION
        WHEN OTHERS THEN
            p_estado := 0;
            p_mensaje := 'Error Oracle: ' || SQLERRM;
    END SP_INSERTAR_TEMPERATURA;

    PROCEDURE SP_ACTUALIZAR_TEMPERATURA(
        p_id_temperatura  IN TEMPERATURA.ID_TEMPERATURA%TYPE,
        p_temp_ambiente   IN TEMPERATURA.TEMP_AMBIENTE%TYPE,
        p_temp_suelo      IN TEMPERATURA.TEMP_SUELO%TYPE,
        p_observacion     IN TEMPERATURA.OBSERVACION%TYPE,
        p_estado          OUT NUMBER,
        p_mensaje         OUT VARCHAR2
    ) AS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM TEMPERATURA WHERE ID_TEMPERATURA = p_id_temperatura;
        IF v_count = 0 THEN
            p_estado := 0; p_mensaje := 'No existe un registro con el ID especificado'; RETURN;
        END IF;

        UPDATE TEMPERATURA
        SET TEMP_AMBIENTE = p_temp_ambiente,
            TEMP_SUELO = p_temp_suelo,
            OBSERVACION = p_observacion
        WHERE ID_TEMPERATURA = p_id_temperatura;

        p_estado := 1; p_mensaje := 'Registro actualizado correctamente';
    EXCEPTION
        WHEN OTHERS THEN
            p_estado := 0; p_mensaje := 'Error Oracle: ' || SQLERRM;
    END SP_ACTUALIZAR_TEMPERATURA;

    PROCEDURE SP_ELIMINAR_TEMPERATURA(
        p_id_temperatura  IN TEMPERATURA.ID_TEMPERATURA%TYPE,
        p_estado          OUT NUMBER,
        p_mensaje         OUT VARCHAR2
    ) AS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM TEMPERATURA WHERE ID_TEMPERATURA = p_id_temperatura;
        IF v_count = 0 THEN
            p_estado := 0; p_mensaje := 'No existe el registro especificado'; RETURN;
        END IF;

        DELETE FROM TEMPERATURA WHERE ID_TEMPERATURA = p_id_temperatura;
        p_estado := 1; p_mensaje := 'Registro eliminado correctamente';
    EXCEPTION
        WHEN OTHERS THEN
            p_estado := 0; p_mensaje := 'Error Oracle: ' || SQLERRM;
    END SP_ELIMINAR_TEMPERATURA;

    PROCEDURE SP_OBTENER_POR_ID(
        p_id_temperatura  IN TEMPERATURA.ID_TEMPERATURA%TYPE,
        p_cursor          OUT SYS_REFCURSOR,
        p_estado          OUT NUMBER,
        p_mensaje         OUT VARCHAR2
    ) AS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM TEMPERATURA WHERE ID_TEMPERATURA = p_id_temperatura;
        IF v_count > 0 THEN
            OPEN p_cursor FOR SELECT * FROM TEMPERATURA WHERE ID_TEMPERATURA = p_id_temperatura;
            p_estado := 1; p_mensaje := 'Registro encontrado';
        ELSE
            OPEN p_cursor FOR SELECT NULL FROM DUAL WHERE 1=0;
            p_estado := 0; p_mensaje := 'No existe un registro con ese ID';
        END IF;
    EXCEPTION
        WHEN OTHERS THEN
            OPEN p_cursor FOR SELECT NULL FROM DUAL WHERE 1=0;
            p_estado := 0; p_mensaje := 'Error Oracle: ' || SQLERRM;
    END SP_OBTENER_POR_ID;

    PROCEDURE SP_MOSTRAR_TODOS(
        p_cursor          OUT SYS_REFCURSOR,
        p_estado          OUT NUMBER,
        p_mensaje         OUT VARCHAR2
    ) AS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM TEMPERATURA;
        OPEN p_cursor FOR SELECT * FROM TEMPERATURA ORDER BY FECHA_HORA DESC;
        p_estado := 1;
        IF v_count > 0 THEN
            p_mensaje := 'Se encontraron ' || v_count || ' registros';
        ELSE
            p_mensaje := 'No existen registros';
        END IF;
    EXCEPTION
        WHEN OTHERS THEN
            OPEN p_cursor FOR SELECT NULL FROM DUAL WHERE 1=0;
            p_estado := 0; p_mensaje := 'Error Oracle: ' || SQLERRM;
    END SP_MOSTRAR_TODOS;
END PKG_TEMPERATURA;
/

-- =========================================================
-- PKG_HISTORIAL_RIEGO (ACTUALIZADO: Soporte ID_PLANTA)
-- =========================================================
CREATE OR REPLACE PACKAGE PKG_HISTORIAL_RIEGO AS
    PROCEDURE SP_INSERTAR_HISTORIAL(
        p_fecha_hora   IN  DATE,
        p_humedad      IN  NUMBER,
        p_temperatura  IN  NUMBER,
        p_id_planta    IN  NUMBER, -- Nuevo parámetro
        p_id_generado  OUT NUMBER,
        p_estado       OUT NUMBER,
        p_mensaje      OUT VARCHAR2
    );
    PROCEDURE SP_BUSCAR_POR_ID(
        p_id IN NUMBER,
        p_cursor OUT SYS_REFCURSOR,
        p_estado OUT NUMBER,
        p_mensaje OUT VARCHAR2
    );
    PROCEDURE SP_MOSTRAR_TODOS(
        p_cursor OUT SYS_REFCURSOR,
        p_estado OUT NUMBER,
        p_mensaje OUT VARCHAR2
    );
END PKG_HISTORIAL_RIEGO;
/

CREATE OR REPLACE PACKAGE BODY PKG_HISTORIAL_RIEGO AS
    PROCEDURE SP_INSERTAR_HISTORIAL(
        p_fecha_hora   IN  DATE,
        p_humedad      IN  NUMBER,
        p_temperatura  IN  NUMBER,
        p_id_planta    IN  NUMBER,
        p_id_generado  OUT NUMBER,
        p_estado       OUT NUMBER,
        p_mensaje      OUT VARCHAR2
    ) AS
    BEGIN
        INSERT INTO historial_riego (
            id_historial_riego, fecha_hora, humedad, temperatura, id_planta
        ) VALUES (
            seq_historial_riego.NEXTVAL, p_fecha_hora, p_humedad, p_temperatura, p_id_planta
        ) RETURNING id_historial_riego INTO p_id_generado;

        p_estado := 1;
        p_mensaje := 'Historial registrado correctamente';
    EXCEPTION
        WHEN OTHERS THEN
            p_estado := 0;
            p_mensaje := SQLERRM;
    END SP_INSERTAR_HISTORIAL;

    PROCEDURE SP_BUSCAR_POR_ID(
        p_id IN NUMBER,
        p_cursor OUT SYS_REFCURSOR,
        p_estado OUT NUMBER,
        p_mensaje OUT VARCHAR2
    ) AS
    BEGIN
        OPEN p_cursor FOR SELECT * FROM historial_riego WHERE id_historial_riego = p_id;
        p_estado := 1; p_mensaje := 'Consulta realizada';
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            p_estado := 0; p_mensaje := 'No existe ese registro';
        WHEN OTHERS THEN
            p_estado := 0; p_mensaje := SQLERRM;
    END SP_BUSCAR_POR_ID;

    PROCEDURE SP_MOSTRAR_TODOS(
        p_cursor OUT SYS_REFCURSOR,
        p_estado OUT NUMBER,
        p_mensaje OUT VARCHAR2
    ) AS
    BEGIN
        OPEN p_cursor FOR SELECT * FROM historial_riego ORDER BY fecha_hora DESC;
        p_estado := 1; p_mensaje := 'Consulta realizada';
    EXCEPTION
        WHEN OTHERS THEN
            p_estado := 0; p_mensaje := SQLERRM;
    END SP_MOSTRAR_TODOS;
END PKG_HISTORIAL_RIEGO;
/

-- =========================================================
-- PKG_REGISTRO_CLIMATICO (ACTUALIZADO: Soporte ID_PLANTA)
-- =========================================================
CREATE OR REPLACE PACKAGE PKG_REGISTRO_CLIMATICO AS
    PROCEDURE SP_INSERTAR_REGISTRO(
        p_humedad_suelo     IN  FLOAT,
        p_humedad_ambiente  IN  FLOAT,
        p_temperatura_amb   IN  FLOAT,
        p_viento            IN  FLOAT,
        p_id_planta         IN  NUMBER, -- Nuevo parámetro
        p_id_generado       OUT NUMBER,
        p_estado            OUT NUMBER,
        p_mensaje           OUT VARCHAR2
    );
    PROCEDURE SP_MOSTRAR_TODOS(
        p_cursor        OUT SYS_REFCURSOR,
        p_estado        OUT NUMBER,
        p_mensaje       OUT VARCHAR2
    );
END PKG_REGISTRO_CLIMATICO;
/

CREATE OR REPLACE PACKAGE BODY PKG_REGISTRO_CLIMATICO AS
    PROCEDURE SP_INSERTAR_REGISTRO(
        p_humedad_suelo     IN  FLOAT,
        p_humedad_ambiente  IN  FLOAT,
        p_temperatura_amb   IN  FLOAT,
        p_viento            IN  FLOAT,
        p_id_planta         IN  NUMBER,
        p_id_generado       OUT NUMBER,
        p_estado            OUT NUMBER,
        p_mensaje           OUT VARCHAR2
    ) AS
    BEGIN
        SELECT seq_registro_climatico.NEXTVAL INTO p_id_generado FROM DUAL;

        INSERT INTO REGISTRO_CLIMATICO (
            ID_REGISTRO, HUMEDAD_SUELO, HUMEDAD_AMBIENTE, TEMPERATURA_AMB, VIENTO, ID_PLANTA
        ) VALUES (
            p_id_generado, p_humedad_suelo, p_humedad_ambiente, p_temperatura_amb, p_viento, p_id_planta
        );

        p_estado := 1;
        p_mensaje := 'Registro climático con planta insertado correctamente';
    EXCEPTION
        WHEN OTHERS THEN
            p_estado := 0;
            p_mensaje := 'Error al insertar registro: ' || SQLERRM;
    END SP_INSERTAR_REGISTRO;

    PROCEDURE SP_MOSTRAR_TODOS(
        p_cursor        OUT SYS_REFCURSOR,
        p_estado        OUT NUMBER,
        p_mensaje       OUT VARCHAR2
    ) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM REGISTRO_CLIMATICO;
        OPEN p_cursor FOR SELECT * FROM REGISTRO_CLIMATICO ORDER BY FECHA_HORA DESC;
        p_estado := 1;
        p_mensaje := 'Se encontraron ' || v_count || ' registros';
    END SP_MOSTRAR_TODOS;
END PKG_REGISTRO_CLIMATICO;
/

-- =========================================================
-- PKG_HISTORIAL_ALERTAS (ACTUALIZADO: Correcciones)
-- =========================================================
CREATE OR REPLACE PACKAGE PKG_HISTORIAL_ALERTAS AS
    PROCEDURE SP_INSERTAR_ALERTA(
        p_fecha_hora     IN  DATE,
        p_tipo_alerta    IN  VARCHAR2,
        p_descripcion    IN  VARCHAR2,
        p_nivel_critico  IN  VARCHAR2,
        p_estado         IN  NUMBER,
        p_id_generado    OUT NUMBER,
        p_resultado      OUT NUMBER,
        p_mensaje        OUT VARCHAR2
    );
    PROCEDURE SP_MOSTRAR_TODOS(
        p_cursor    OUT SYS_REFCURSOR,
        p_resultado OUT NUMBER,
        p_mensaje   OUT VARCHAR2
    );
END PKG_HISTORIAL_ALERTAS;
/

CREATE OR REPLACE PACKAGE BODY PKG_HISTORIAL_ALERTAS AS
    PROCEDURE SP_INSERTAR_ALERTA(
        p_fecha_hora     IN  DATE,
        p_tipo_alerta    IN  VARCHAR2,
        p_descripcion    IN  VARCHAR2,
        p_nivel_critico  IN  VARCHAR2,
        p_estado         IN  NUMBER,
        p_id_generado    OUT NUMBER,
        p_resultado      OUT NUMBER,
        p_mensaje        OUT VARCHAR2
    ) AS
    BEGIN
        SELECT seq_alertas.NEXTVAL INTO p_id_generado FROM DUAL;

        INSERT INTO Historial_Alertas (
            id_alerta, fecha_hora, tipo_alerta, descripcion, nivel_critico, estado
        ) VALUES (
            p_id_generado, p_fecha_hora, p_tipo_alerta, p_descripcion, p_nivel_critico, p_estado
        );

        p_resultado := 1;
        p_mensaje := 'Alerta registrada correctamente';
    EXCEPTION
        WHEN OTHERS THEN
            p_resultado := 0;
            p_mensaje := 'Error al registrar alerta: ' || SQLERRM;
            p_id_generado := 0;
    END SP_INSERTAR_ALERTA;

    PROCEDURE SP_MOSTRAR_TODOS(
        p_cursor    OUT SYS_REFCURSOR,
        p_resultado OUT NUMBER,
        p_mensaje   OUT VARCHAR2
    ) AS
    BEGIN
        OPEN p_cursor FOR SELECT * FROM Historial_Alertas ORDER BY fecha_hora DESC;
        p_resultado := 1;
        p_mensaje := 'Alertas listadas correctamente';
    EXCEPTION
        WHEN OTHERS THEN
            p_resultado := 0;
            p_mensaje := 'Error al listar: ' || SQLERRM;
    END SP_MOSTRAR_TODOS;
END PKG_HISTORIAL_ALERTAS;
/


---MODIFICACION CLIMA
CREATE OR REPLACE PACKAGE BODY PKG_REGISTRO_CLIMATICO AS

    PROCEDURE SP_INSERTAR_REGISTRO(
        p_humedad_suelo     IN  FLOAT,
        p_humedad_ambiente  IN  FLOAT,
        p_temperatura_amb   IN  FLOAT,
        p_viento            IN  FLOAT,
        p_id_planta         IN  NUMBER,
        p_id_generado       OUT NUMBER,
        p_estado            OUT NUMBER,
        p_mensaje           OUT VARCHAR2
    ) AS
        v_new_id NUMBER;
    BEGIN
        -- 1. Obtener el ID manualmente para evitar conflictos con RETURNING
        SELECT seq_registro_climatico.NEXTVAL INTO v_new_id FROM DUAL;

        -- 2. Insertar usando ese ID
        INSERT INTO REGISTRO_CLIMATICO (
            ID_REGISTRO, HUMEDAD_SUELO, HUMEDAD_AMBIENTE, TEMPERATURA_AMB, VIENTO, ID_PLANTA
        ) VALUES (
            v_new_id, p_humedad_suelo, p_humedad_ambiente, p_temperatura_amb, p_viento, p_id_planta
        );

        -- 3. Confirmar
        COMMIT;

        -- 4. Devolver resultados
        p_id_generado := v_new_id;
        p_estado := 1;
        p_mensaje := 'Registro climático guardado correctamente';
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            p_estado := 0;
            p_mensaje := 'Error BD: ' || SQLERRM;
            p_id_generado := 0;
    END SP_INSERTAR_REGISTRO;

    PROCEDURE SP_MOSTRAR_TODOS(
        p_cursor        OUT SYS_REFCURSOR,
        p_estado        OUT NUMBER,
        p_mensaje       OUT VARCHAR2
    ) IS
    BEGIN
        OPEN p_cursor FOR SELECT * FROM REGISTRO_CLIMATICO ORDER BY FECHA_HORA DESC;
        p_estado := 1;
        p_mensaje := 'Registros encontrados';
    END SP_MOSTRAR_TODOS;

END PKG_REGISTRO_CLIMATICO;
/

---MODIFICAR TEMPERATURA

CREATE OR REPLACE PACKAGE PKG_TEMPERATURA AS

    -- INSERTAR
    PROCEDURE SP_INSERTAR_TEMPERATURA(
        p_temp_ambiente   IN FLOAT,
        p_temp_suelo      IN FLOAT,
        p_observacion     IN VARCHAR2,
        p_id_planta       IN NUMBER,
        p_id_generado     OUT NUMBER,
        p_estado          OUT NUMBER,
        p_mensaje         OUT VARCHAR2
    );

    -- ACTUALIZAR
    PROCEDURE SP_ACTUALIZAR_TEMPERATURA(
        p_id_temperatura  IN NUMBER,
        p_temp_ambiente   IN FLOAT,
        p_temp_suelo      IN FLOAT,
        p_observacion     IN VARCHAR2,
        p_estado          OUT NUMBER,
        p_mensaje         OUT VARCHAR2
    );

    -- ELIMINAR
    PROCEDURE SP_ELIMINAR_TEMPERATURA(
        p_id_temperatura  IN NUMBER,
        p_estado          OUT NUMBER,
        p_mensaje         OUT VARCHAR2
    );

    -- OBTENER POR ID
    PROCEDURE SP_OBTENER_POR_ID(
        p_id_temperatura  IN NUMBER,
        p_cursor          OUT SYS_REFCURSOR,
        p_estado          OUT NUMBER,
        p_mensaje         OUT VARCHAR2
    );

    -- MOSTRAR TODOS
    PROCEDURE SP_MOSTRAR_TODOS(
        p_cursor          OUT SYS_REFCURSOR,
        p_estado          OUT NUMBER,
        p_mensaje         OUT VARCHAR2
    );

END PKG_TEMPERATURA;
/


CREATE OR REPLACE PACKAGE BODY PKG_TEMPERATURA AS

    -- ==============================================================
    -- INSERTAR (CON COMMIT Y FLOAT)
    -- ==============================================================
    PROCEDURE SP_INSERTAR_TEMPERATURA(
        p_temp_ambiente   IN FLOAT,
        p_temp_suelo      IN FLOAT,
        p_observacion     IN VARCHAR2,
        p_id_planta       IN NUMBER,
        p_id_generado     OUT NUMBER,
        p_estado          OUT NUMBER,
        p_mensaje         OUT VARCHAR2
    ) AS
        v_new_id NUMBER;
    BEGIN
        -- 1. Obtener ID manualmente
        SELECT seq_temperatura.NEXTVAL INTO v_new_id FROM DUAL;

        -- 2. Insertar
        INSERT INTO TEMPERATURA (
            ID_TEMPERATURA, TEMP_AMBIENTE, TEMP_SUELO, OBSERVACION, ID_PLANTA
        ) VALUES (
            v_new_id, p_temp_ambiente, p_temp_suelo, p_observacion, p_id_planta
        );

        -- 3. GUARDAR CAMBIOS
        COMMIT;

        p_id_generado := v_new_id;
        p_estado := 1;
        p_mensaje := 'Temperatura guardada correctamente';
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            p_estado := 0;
            p_mensaje := 'Error Oracle: ' || SQLERRM;
            p_id_generado := 0;
    END SP_INSERTAR_TEMPERATURA;

    -- ==============================================================
    -- ACTUALIZAR
    -- ==============================================================
    PROCEDURE SP_ACTUALIZAR_TEMPERATURA(
        p_id_temperatura  IN NUMBER,
        p_temp_ambiente   IN FLOAT,
        p_temp_suelo      IN FLOAT,
        p_observacion     IN VARCHAR2,
        p_estado          OUT NUMBER,
        p_mensaje         OUT VARCHAR2
    ) AS
    BEGIN
        UPDATE TEMPERATURA
        SET TEMP_AMBIENTE = p_temp_ambiente,
            TEMP_SUELO = p_temp_suelo,
            OBSERVACION = p_observacion
        WHERE ID_TEMPERATURA = p_id_temperatura;

        IF SQL%ROWCOUNT > 0 THEN
            COMMIT; -- GUARDAR CAMBIOS
            p_estado := 1; 
            p_mensaje := 'Actualizado correctamente';
        ELSE
            p_estado := 0; 
            p_mensaje := 'No se encontró el ID';
        END IF;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            p_estado := 0; 
            p_mensaje := SQLERRM;
    END SP_ACTUALIZAR_TEMPERATURA;

    -- ==============================================================
    -- ELIMINAR
    -- ==============================================================
    PROCEDURE SP_ELIMINAR_TEMPERATURA(
        p_id_temperatura  IN NUMBER,
        p_estado          OUT NUMBER,
        p_mensaje         OUT VARCHAR2
    ) AS
    BEGIN
        DELETE FROM TEMPERATURA WHERE ID_TEMPERATURA = p_id_temperatura;
        
        IF SQL%ROWCOUNT > 0 THEN
            COMMIT; -- GUARDAR CAMBIOS
            p_estado := 1; 
            p_mensaje := 'Eliminado correctamente';
        ELSE
            p_estado := 0; 
            p_mensaje := 'No encontrado';
        END IF;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            p_estado := 0; p_mensaje := SQLERRM;
    END SP_ELIMINAR_TEMPERATURA;

    -- ==============================================================
    -- OBTENER POR ID
    -- ==============================================================
    PROCEDURE SP_OBTENER_POR_ID(
        p_id_temperatura  IN NUMBER,
        p_cursor          OUT SYS_REFCURSOR,
        p_estado          OUT NUMBER,
        p_mensaje         OUT VARCHAR2
    ) AS
    BEGIN
        OPEN p_cursor FOR SELECT * FROM TEMPERATURA WHERE ID_TEMPERATURA = p_id_temperatura;
        p_estado := 1; 
        p_mensaje := 'Consulta ejecutada';
    END SP_OBTENER_POR_ID;

    -- ==============================================================
    -- MOSTRAR TODOS
    -- ==============================================================
    PROCEDURE SP_MOSTRAR_TODOS(
        p_cursor          OUT SYS_REFCURSOR,
        p_estado          OUT NUMBER,
        p_mensaje         OUT VARCHAR2
    ) AS
    BEGIN
        OPEN p_cursor FOR SELECT * FROM TEMPERATURA ORDER BY FECHA_HORA DESC;
        p_estado := 1; 
        p_mensaje := 'Consulta ejecutada';
    END SP_MOSTRAR_TODOS;

END PKG_TEMPERATURA; 
/


---MODIFICAR HISTORILA RIEGO
-- 1. Agregar columna a la tabla
ALTER TABLE HISTORIAL_RIEGO ADD TIPO_RIEGO VARCHAR2(20);

-- 2. Actualizar el Procedimiento de Insertar (Package Body)
CREATE OR REPLACE PACKAGE BODY PKG_HISTORIAL_RIEGO AS

    PROCEDURE SP_INSERTAR_HISTORIAL(
        p_fecha_hora   IN  DATE,
        p_humedad      IN  NUMBER,
        p_temperatura  IN  NUMBER,
        p_id_planta    IN  NUMBER,
        p_tipo_riego   IN  VARCHAR2, -- ✅ Nuevo parámetro
        p_id_generado  OUT NUMBER,
        p_estado       OUT NUMBER,
        p_mensaje      OUT VARCHAR2
    ) AS
    BEGIN
        INSERT INTO historial_riego (
            id_historial_riego, fecha_hora, humedad, temperatura, id_planta, tipo_riego
        ) VALUES (
            seq_historial_riego.NEXTVAL, p_fecha_hora, p_humedad, p_temperatura, p_id_planta, p_tipo_riego
        ) RETURNING id_historial_riego INTO p_id_generado;

        p_estado := 1;
        p_mensaje := 'Historial registrado correctamente';
    EXCEPTION
        WHEN OTHERS THEN
            p_estado := 0;
            p_mensaje := SQLERRM;
    END SP_INSERTAR_HISTORIAL;

    -- (Los otros procedimientos buscar_por_id y mostrar_todos se mantienen, 
    -- pero el SELECT * ya traerá la nueva columna automáticamente)
    PROCEDURE SP_BUSCAR_POR_ID(p_id IN NUMBER, p_cursor OUT SYS_REFCURSOR, p_estado OUT NUMBER, p_mensaje OUT VARCHAR2) AS
    BEGIN
        OPEN p_cursor FOR SELECT * FROM historial_riego WHERE id_historial_riego = p_id;
        p_estado := 1; p_mensaje := 'Consulta realizada';
    END SP_BUSCAR_POR_ID;

    PROCEDURE SP_MOSTRAR_TODOS(p_cursor OUT SYS_REFCURSOR, p_estado OUT NUMBER, p_mensaje OUT VARCHAR2) AS
    BEGIN
        OPEN p_cursor FOR SELECT * FROM historial_riego ORDER BY fecha_hora DESC;
        p_estado := 1; p_mensaje := 'Consulta realizada';
    END SP_MOSTRAR_TODOS;

END PKG_HISTORIAL_RIEGO;
/
COMMIT;


---MODIFICAR HISTORIAL REIGO
-- 1. Asegurar que la columna existe
ALTER TABLE HISTORIAL_RIEGO ADD TIPO_RIEGO VARCHAR2(20);

-- 2. Actualizar el PAQUETE (Package Body) para aceptar el nuevo parámetro
CREATE OR REPLACE PACKAGE BODY PKG_HISTORIAL_RIEGO AS

    PROCEDURE SP_INSERTAR_HISTORIAL(
        p_fecha_hora   IN  DATE,
        p_humedad      IN  NUMBER,
        p_temperatura  IN  NUMBER,
        p_id_planta    IN  NUMBER,
        p_tipo_riego   IN  VARCHAR2, -- ✅ Nuevo parámetro necesario
        p_id_generado  OUT NUMBER,
        p_estado       OUT NUMBER,
        p_mensaje      OUT VARCHAR2
    ) AS
    BEGIN
        INSERT INTO historial_riego (
            id_historial_riego, fecha_hora, humedad, temperatura, id_planta, tipo_riego
        ) VALUES (
            seq_historial_riego.NEXTVAL, p_fecha_hora, p_humedad, p_temperatura, p_id_planta, p_tipo_riego
        ) RETURNING id_historial_riego INTO p_id_generado;

        p_estado := 1;
        p_mensaje := 'Historial registrado correctamente';
    EXCEPTION
        WHEN OTHERS THEN
            p_estado := 0;
            p_mensaje := SQLERRM;
    END SP_INSERTAR_HISTORIAL;

    PROCEDURE SP_BUSCAR_POR_ID(p_id IN NUMBER, p_cursor OUT SYS_REFCURSOR, p_estado OUT NUMBER, p_mensaje OUT VARCHAR2) AS
    BEGIN
        OPEN p_cursor FOR SELECT * FROM historial_riego WHERE id_historial_riego = p_id;
        p_estado := 1; p_mensaje := 'Consulta realizada';
    END SP_BUSCAR_POR_ID;

    PROCEDURE SP_MOSTRAR_TODOS(p_cursor OUT SYS_REFCURSOR, p_estado OUT NUMBER, p_mensaje OUT VARCHAR2) AS
    BEGIN
        -- ✅ Incluimos la nueva columna y los JOINs
        OPEN p_cursor FOR 
            SELECT h.ID_HISTORIAL_RIEGO, h.FECHA_HORA, h.HUMEDAD, h.TEMPERATURA, h.ID_PLANTA, h.TIPO_RIEGO,
                   c.NOMBRE_PLANTA, u.NOMBRE_USUARIO as PROPIETARIO
            FROM HISTORIAL_RIEGO h
            LEFT JOIN CULTIVO c ON h.ID_PLANTA = c.ID_PLANTA
            LEFT JOIN USUARIO u ON c.ID_USUARIO = u.CEDULA
            ORDER BY h.FECHA_HORA DESC;
            
        p_estado := 1; p_mensaje := 'Consulta realizada';
    END SP_MOSTRAR_TODOS;

END PKG_HISTORIAL_RIEGO;
/
COMMIT;

-- 1. Agrega la columna si no existe
ALTER TABLE HISTORIAL_RIEGO ADD TIPO_RIEGO VARCHAR2(20);

-- 2. Rellena los datos vacíos antiguos con 'Manual' para evitar errores
UPDATE HISTORIAL_RIEGO SET TIPO_RIEGO = 'Manual' WHERE TIPO_RIEGO IS NULL;
COMMIT;}

-- 1. Actualizar el Procedimiento para que acepte el nuevo parámetro
CREATE OR REPLACE PACKAGE BODY PKG_HISTORIAL_RIEGO AS

    PROCEDURE SP_INSERTAR_HISTORIAL(
        p_fecha_hora   IN  DATE,
        p_humedad      IN  NUMBER,
        p_temperatura  IN  NUMBER,
        p_id_planta    IN  NUMBER,
        p_tipo_riego   IN  VARCHAR2, -- ✅ Este es el parámetro nuevo
        p_id_generado  OUT NUMBER,
        p_estado       OUT NUMBER,
        p_mensaje      OUT VARCHAR2
    ) AS
    BEGIN
        INSERT INTO historial_riego (
            id_historial_riego, fecha_hora, humedad, temperatura, id_planta, tipo_riego
        ) VALUES (
            seq_historial_riego.NEXTVAL, p_fecha_hora, p_humedad, p_temperatura, p_id_planta, p_tipo_riego
        ) RETURNING id_historial_riego INTO p_id_generado;

        p_estado := 1;
        p_mensaje := 'Historial registrado correctamente';
    EXCEPTION
        WHEN OTHERS THEN
            p_estado := 0;
            p_mensaje := SQLERRM;
    END SP_INSERTAR_HISTORIAL;

    -- (Mantener los otros procedimientos igual...)
    PROCEDURE SP_BUSCAR_POR_ID(p_id IN NUMBER, p_cursor OUT SYS_REFCURSOR, p_estado OUT NUMBER, p_mensaje OUT VARCHAR2) AS
    BEGIN
        OPEN p_cursor FOR SELECT * FROM historial_riego WHERE id_historial_riego = p_id;
        p_estado := 1; p_mensaje := 'Consulta realizada';
    END SP_BUSCAR_POR_ID;

    PROCEDURE SP_MOSTRAR_TODOS(p_cursor OUT SYS_REFCURSOR, p_estado OUT NUMBER, p_mensaje OUT VARCHAR2) AS
    BEGIN
        OPEN p_cursor FOR 
            SELECT h.ID_HISTORIAL_RIEGO, h.FECHA_HORA, h.HUMEDAD, h.TEMPERATURA, h.ID_PLANTA, h.TIPO_RIEGO,
                   c.NOMBRE_PLANTA, u.NOMBRE_USUARIO as PROPIETARIO
            FROM HISTORIAL_RIEGO h
            LEFT JOIN CULTIVO c ON h.ID_PLANTA = c.ID_PLANTA
            LEFT JOIN USUARIO u ON c.ID_USUARIO = u.CEDULA
            ORDER BY h.FECHA_HORA DESC;
        p_estado := 1; p_mensaje := 'Consulta realizada';
    END SP_MOSTRAR_TODOS;

END PKG_HISTORIAL_RIEGO;
/
COMMIT;




--------------------------------------------------------
-- 1. ACTUALIZAR LA ESPECIFICACIÓN (CABECERA)
--------------------------------------------------------
CREATE OR REPLACE PACKAGE PKG_HISTORIAL_RIEGO AS

    -- Se agrega p_tipo_riego aquí
    PROCEDURE SP_INSERTAR_HISTORIAL(
        p_fecha_hora   IN  DATE,
        p_humedad      IN  NUMBER,
        p_temperatura  IN  NUMBER,
        p_id_planta    IN  NUMBER,
        p_tipo_riego   IN  VARCHAR2, -- ✅ Nuevo parámetro obligatorio
        p_id_generado  OUT NUMBER,
        p_estado       OUT NUMBER,
        p_mensaje      OUT VARCHAR2
    );

    PROCEDURE SP_BUSCAR_POR_ID(
        p_id IN NUMBER,
        p_cursor OUT SYS_REFCURSOR,
        p_estado OUT NUMBER,
        p_mensaje OUT VARCHAR2
    );

    PROCEDURE SP_MOSTRAR_TODOS(
        p_cursor OUT SYS_REFCURSOR,
        p_estado OUT NUMBER,
        p_mensaje OUT VARCHAR2
    );

END PKG_HISTORIAL_RIEGO;
/

--------------------------------------------------------
-- 2. ACTUALIZAR EL CUERPO (LÓGICA)
--------------------------------------------------------
CREATE OR REPLACE PACKAGE BODY PKG_HISTORIAL_RIEGO AS

    -- INSERTAR
    PROCEDURE SP_INSERTAR_HISTORIAL(
        p_fecha_hora   IN  DATE,
        p_humedad      IN  NUMBER,
        p_temperatura  IN  NUMBER,
        p_id_planta    IN  NUMBER,
        p_tipo_riego   IN  VARCHAR2, -- ✅ Debe coincidir con la cabecera
        p_id_generado  OUT NUMBER,
        p_estado       OUT NUMBER,
        p_mensaje      OUT VARCHAR2
    ) AS
    BEGIN
        INSERT INTO historial_riego (
            id_historial_riego, fecha_hora, humedad, temperatura, id_planta, tipo_riego
        ) VALUES (
            seq_historial_riego.NEXTVAL, p_fecha_hora, p_humedad, p_temperatura, p_id_planta, p_tipo_riego
        ) RETURNING id_historial_riego INTO p_id_generado;

        p_estado := 1;
        p_mensaje := 'Historial registrado correctamente';
    EXCEPTION
        WHEN OTHERS THEN
            p_estado := 0;
            p_mensaje := SQLERRM;
    END SP_INSERTAR_HISTORIAL;

    -- BUSCAR POR ID
    PROCEDURE SP_BUSCAR_POR_ID(
        p_id IN NUMBER,
        p_cursor OUT SYS_REFCURSOR,
        p_estado OUT NUMBER,
        p_mensaje OUT VARCHAR2
    ) AS
    BEGIN
        OPEN p_cursor FOR SELECT * FROM historial_riego WHERE id_historial_riego = p_id;
        p_estado := 1; p_mensaje := 'Consulta realizada';
    END SP_BUSCAR_POR_ID;

    -- MOSTRAR TODOS (Actualizado con JOINs y Tipo)
    PROCEDURE SP_MOSTRAR_TODOS(
        p_cursor OUT SYS_REFCURSOR,
        p_estado OUT NUMBER,
        p_mensaje OUT VARCHAR2
    ) AS
    BEGIN
        OPEN p_cursor FOR 
            SELECT h.ID_HISTORIAL_RIEGO, h.FECHA_HORA, h.HUMEDAD, h.TEMPERATURA, h.ID_PLANTA, h.TIPO_RIEGO,
                   c.NOMBRE_PLANTA, u.NOMBRE_USUARIO as PROPIETARIO
            FROM HISTORIAL_RIEGO h
            LEFT JOIN CULTIVO c ON h.ID_PLANTA = c.ID_PLANTA
            LEFT JOIN USUARIO u ON c.ID_USUARIO = u.CEDULA
            ORDER BY h.FECHA_HORA DESC;
            
        p_estado := 1; p_mensaje := 'Consulta realizada';
    END SP_MOSTRAR_TODOS;

END PKG_HISTORIAL_RIEGO;
/
